# Generated by Django 4.1.dev20220319144148 on 2022-03-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropDownModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropdown_choices', models.CharField(choices=[('profile', 'Profile'), ('settings', 'Settings'), ('logout', 'Logout')], default='profile', max_length=10)),
            ],
        ),
    ]
