# Generated by Django 4.0.3 on 2022-03-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchingparty', '0002_profile_delete_dropdownmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaTitle', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=20)),
                ('eventDate', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
