# Generated by Django 4.1.dev20220319144148 on 2022-03-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchingparty', '0002_profile_delete_dropdownmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(default='This is a default interest. Please edit this in the profile settings if you want people to see your interests.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviews',
            field=models.TextField(default='This is a default review.'),
        ),
    ]
