# Generated by Django 4.1.dev20220319144148 on 2022-03-24 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchingparty', '0003_event'),
        ('watchingparty', '0003_profile_interests_profile_reviews'),
    ]

    operations = [
    ]
