# Generated by Django 4.1.dev20220319144148 on 2022-03-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchingparty', '0004_merge_20220324_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventDate',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
