# Generated by Django 4.1.dev20220319144148 on 2022-03-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchingparty', '0005_alter_event_eventdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favoriteMovies',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favoriteTVShows',
        ),
        migrations.AddField(
            model_name='profile',
            name='fifthFavoriteMovie',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='fifthFavoriteTVShow',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstFavoriteMovie',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstFavoriteTVShow',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='fourthFavoriteMovie',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='fourthFavoriteTVShow',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='secondFavoriteMovie',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='secondFavoriteTVShow',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='thirdFavoriteMovie',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='thirdFavoriteTVShow',
            field=models.CharField(default='', max_length=200),
        ),
    ]
