# Generated by Django 4.1.dev20220319144148 on 2022-03-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchingparty', '0006_remove_profile_favoritemovies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
