# Generated by Django 4.1.dev20220319144148 on 2022-04-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchingparty', '0009_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='Charlottesville', max_length=200),
        ),
    ]
