# Generated by Django 4.1.dev20220319144148 on 2022-04-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchingparty', '0010_event_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(default='375 Merchant Walk Sq', max_length=200),
        ),
    ]
