# Generated by Django 4.0.2 on 2022-04-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchingparty', '0014_meeting_movietitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participant',
            field=models.ManyToManyField(to='watchingparty.Profile'),
        ),
    ]
